-- ENSURE ALL TRACKING COLUMNS EXIST IN THE LOANS TABLE
-- RUN THIS IN YOUR SUPABASE SQL EDITOR

ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS staff_id TEXT;
ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS staff_name TEXT;
ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS center_name TEXT;
ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS member_name TEXT;
ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS member_cibil TEXT;

-- This will allow the backend to successfully insert loan applications.
