-- 1. Create STAFF table ONLY if it doesn't exist
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    name TEXT,
    role TEXT DEFAULT 'Relationship Officer',
    is_password_set BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insert the login you want to use
-- Note: If you already inserted this, it might give an error, which is fine.
INSERT INTO staff (staff_id, password, name, role) 
VALUES ('STF014', '100816', 'Relationship Officer', 'Relationship Officer')
ON CONFLICT (staff_id) DO NOTHING;

-- 3. Disable RLS just for this table
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
