-- RUN THIS IN SUPABASE SQL EDITOR TO FIX ALL PERMISSION ERRORS

ALTER TABLE centers DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE loans DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;

-- This ensures ANY key (including the one we are using) can read/write the data.
