-- FINAL LOAN APPLICATION SCHEMA (SUPABASE)
-- Drop existing tables if you want to start fresh (WARNING: DELETES DATA)
-- DROP TABLE IF EXISTS loans;
-- DROP TABLE IF EXISTS members;
-- DROP TABLE IF EXISTS centers;
-- DROP TABLE IF EXISTS staff;

-- 1. CENTERS TABLE
CREATE TABLE IF NOT EXISTS centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. MEMBERS TABLE
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id BIGINT REFERENCES centers(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. STAFF TABLE
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id TEXT UNIQUE NOT NULL, -- e.g., STF014
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'Relationship Officer',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. LOANS TABLE (ALL COLUMNS)
CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT,
    center_id BIGINT,
    
    -- Tracking Names (Denormalized for easy viewing)
    staff_id TEXT,
    staff_name TEXT,
    center_name TEXT,
    member_name TEXT,

    -- Member Info
    member_cibil TEXT,
    person_name TEXT,
    date_of_birth DATE,
    gender TEXT,
    religion TEXT,
    marital_status TEXT,
    aadhar_no TEXT,
    member_work TEXT,
    annual_income TEXT,

    -- Nominee Info
    nominee_name TEXT,
    nominee_dob DATE,
    nominee_gender TEXT,
    nominee_religion TEXT,
    nominee_marital_status TEXT,
    nominee_relationship TEXT,
    nominee_business TEXT,

    -- Contact & Address
    mobile_no TEXT,
    nominee_mobile TEXT,
    member_email TEXT,
    address TEXT,
    pincode TEXT,

    -- Document URLs (Uploaded to Supabase Storage)
    member_aadhaar_front_url TEXT,
    member_aadhaar_back_url TEXT,
    nominee_aadhaar_front_url TEXT,
    nominee_aadhaar_back_url TEXT,
    pan_card_url TEXT,
    form_image_url TEXT,
    signature_url TEXT,
    member_photo_url TEXT,
    passbook_image_url TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DISABLE RLS FOR EVERYTHING (Development only)
ALTER TABLE centers DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE loans DISABLE ROW LEVEL SECURITY;

-- INSERT INITIAL STAFF
INSERT INTO staff (staff_id, password, name, role)
VALUES ('STF014', '100816', 'Test Staff', 'Relationship Officer')
ON CONFLICT (staff_id) DO NOTHING;
